### ISSUE TITLE
Register the CoreMLSuite with ComfyUI Manager

### ISSUE THREAD

**Issue by alessandroperilli** [aszc-dev/ComfyUI-CoreMLSuite#1]
That would be very handy to keep up with the updates.

[https://github.com/ltdrdata/ComfyUI-Manager#how-to-register-your-custom-node-into-comfyui-manager](https://github.com/ltdrdata/ComfyUI-Manager#how-to-register-your-custom-node-into-comfyui-manager)

**Comment by aszc-dev** [comment]
Thanks for the suggestion!
Seems that it's already there :)

**Comment by alessandroperilli** [comment]
It didn't when I opened this issue. It's pleasing to see ComfyUI maintainer as fast as always. Watching your progress with much interest.
