### ISSUE TITLE
I got this error after installing : ImportError: cannot import name 'ModelSamplingDiscreteLCM' from 'comfy_extras.nodes_model_advanced'

### ISSUE THREAD

**Issue by x4080** [aszc-dev/ComfyUI-CoreMLSuite#28]
It seems there's no ModelSamplingDiscreteLCM in comfy_extras.nodes_model_advanced file

Did I do something wrong ?

Thanks

**Comment by quantumbeep** [comment]
same issue. i think the update broke the coreml suite. i checked the node modules advanced py file. looks like maybe module name change.. but not sure.

**Comment by cchance27** [comment]
you need to rename ModelSamplingDiscreteLCM in custom_nodes/ComfyUI-CoreMLSuite/coreml_suite/lcm/utils.py to  ModelSamplingDiscreteDistilled at the top

I'll submit a PR to fix it, they refactored things recently in comfy

Fixed in #29

**Comment by x4080** [comment]
yes this fix it

thanks @cchance27

**Comment by aszc-dev** [comment]
Thank you for the fix 👍

**Comment by rovo79** [comment]
Awesome, and running the update via comfyui manager pulled it in!

**Comment by rovo79** [comment]
I spoke to soon... after I refreshed my browser, CoreMLsuite was broken. Maybe it's unrelated...?
<img width="1289" alt="image" src="https://github.com/aszc-dev/ComfyUI-CoreMLSuite/assets/117691/f2b701f8-13ba-4845-b874-9b7073495bda">

Spotted this error in the log:

```
Update custom node 'Core ML Suite for ComfyUI'
Update: ['https://github.com/aszc-dev/ComfyUI-CoreMLSuite']
path=/Users/rovo/ComfyUI/custom_nodes/ComfyUI-CoreMLSuite / repo.is_dirty: False
```

....

```
Traceback (most recent call last):
  File "/Users/rovo/ComfyUI/nodes.py", line 1735, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/rovo/ComfyUI/custom_nodes/ComfyUI-CoreMLSuite/__init__.py", line 6, in <module>
    from coreml_suite.nodes import (
  File "/Users/rovo/ComfyUI/custom_nodes/ComfyUI-CoreMLSuite/coreml_suite/nodes.py", line 11, in <module>
    from coreml_suite.lcm.utils import add_lcm_model_options, lcm_patch, is_lcm
  File "/Users/rovo/ComfyUI/custom_nodes/ComfyUI-CoreMLSuite/coreml_suite/lcm/utils.py", line 4, in <module>
    from comfy_extras.nodes_model_advanced import ModelSamplingDiscreteDistilled, LCM
ImportError: cannot import name 'ModelSamplingDiscreteDistilled' from 'comfy_extras.nodes_model_advanced' (/Users/rovo/ComfyUI/comfy_extras/nodes_model_advanced.py)

Cannot import /Users/rovo/ComfyUI/custom_nodes/ComfyUI-CoreMLSuite module for custom nodes: cannot import name 'ModelSamplingDiscreteDistilled' from 'comfy_extras.nodes_model_advanced' (/Users/rovo/ComfyUI/comfy_extras/nodes_model_advanced.py)

```

**Comment by rovo79** [comment]
I went back to the command line, `/ComfyUI/custom_nodes/ComfyUI-CoreMLSuite ran` , `pip install -r requirements.txt` again, and that resolved it.
