### ISSUE TITLE
Module will not load

### ISSUE THREAD

**Issue by francisjervis** [aszc-dev/ComfyUI-CoreMLSuite#37]
Fresh install, I'm not sure if the torch version warning is actually relevant. On MacOS 14.4.

`scikit-learn version 1.4.1.post1 is not supported. Minimum required version: 0.17. Maximum required version: 1.1.2. Disabling scikit-learn conversion API.
Torch version 2.2.1 has not been tested with coremltools. You may run into unexpected errors. Torch 2.1.0 is the most recent version that has been tested.
/Users/francis/Library/Python/3.9/lib/python/site-packages/diffusers/utils/outputs.py:63: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
Traceback (most recent call last):
  File "/Users/francis/ComfyUI/nodes.py", line 1887, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/francis/ComfyUI/custom_nodes/ComfyUI-CoreMLSuite-main/__init__.py", line 6, in <module>
    from coreml_suite.nodes import (
  File "/ComfyUI/custom_nodes/ComfyUI-CoreMLSuite-main/coreml_suite/nodes.py", line 9, in <module>
    from coreml_suite import converter
  File "/ComfyUI/custom_nodes/ComfyUI-CoreMLSuite-main/coreml_suite/converter.py", line 318, in <module>
    lora_weights: list[tuple[str | os.PathLike, float]] = None,
TypeError: unsupported operand type(s) for |: 'type' and 'ABCMeta'`

**Comment by aszc-dev** [comment]
Hello. I don't know if your still facing this issue, but I think I know what may be causing it. The "|" operator is not interpreted correctly. Since it's [usage for union types](https://peps.python.org/pep-0604/) was introduced in python 3.10, you're most probably using an older version of python. Please try using newer version (>3.10) and see if the problem persists.

**Comment by jonathanstanley** [comment]
fwiw, i kept hitting this issue also. to ensure the install process is correct and correct versions, i created a short script: https://github.com/comfyanonymous/ComfyUI/discussions/3283#discussion-6522149

**Comment by aszc-dev** [comment]
Hello,

I’m closing this issue since I’ve changed the syntax to be backwards compatible with older versions of Python.

Cheers,
Adrian
