### ISSUE TITLE
compatibility issue?

### ISSUE THREAD

**Issue by ltdrdata** [aszc-dev/ComfyUI-CoreMLSuite#9]
A CoreML user reports that after [1777b54d021](https://github.com/comfyanonymous/ComfyUI/commit/1777b54d0217e77a6a64b0a587b9b11a48e3bf02) patch of ComfyUI, only noise image is generated.

**Comment by aszc-dev** [comment]
Thanks.
Yes, this patch caught me off guard as I was working on LCM stuff. I think I've managed to adapt the main functionality to this new flow, at least the workflows from readme should work properly.

**Comment by ltdrdata** [comment]
Patch confirmed. Thx.
